version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_represent
    restart: always
    environment:
      POSTGRES_USER: andersonfuzz
      POSTGRES_PASSWORD: andersonfuzz
      POSTGRES_DB: represent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
